/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uaspl;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author Andy
 */
public class FormProgram extends javax.swing.JFrame {

    /**
     * Creates new form FormProgram
     */
private List<Object[]> nlist = new ArrayList<>();
private TableRowSorter <TableModel> rowSorter ;
    public FormProgram() {
        initComponents();
    System.out.println("==================================================");
    System.out.println("=== Selamat Di Program Converter by Andy Huang ===");
    System.out.println("==================================================");
    System.out.println("Anda Memasukan Data : " + InputAngka.getText());
        ImageIcon imageIcon = new ImageIcon("res/logo.png");
        setIconImage(imageIcon.getImage());
        rowSorter = new TableRowSorter<>(tableout.getModel());
        tableout.setRowSorter(rowSorter);
        InSearch.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = InSearch.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    for (int i = 0; i < nlist.size(); i++){
                        if (nlist.get(i)[0].toString().matches("(?i)" + text)){
                            System.out.println(
                                            "\nHasil Dari Pencarian Anda : " +
                                            "\nDecimal : " + nlist.get(i)[0].toString() +
                                            "\nBiner : " + nlist.get(i)[1].toString() +
                                            "\nOctal : " + nlist.get(i)[2].toString() +
                                            "\nHexadecimal : " + nlist.get(i)[3].toString() 
                );
            }
        }
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = InSearch.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                    for (int i = 0; i < nlist.size(); i++){
                        if (nlist.get(i)[0].toString().matches("(?i)" + text)){
                            System.out.println(
                                            "\nHasil Dari Pencarian Anda : " +
                                            "\nDecimal : " + nlist.get(i)[0].toString() +
                                            "\nBiner : " + nlist.get(i)[1].toString() +
                                            "\nOctal : " + nlist.get(i)[2].toString() +
                                            "\nHexadecimal : " + nlist.get(i)[3].toString() 
                );
            }
        }
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputAngka = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableout = new javax.swing.JTable();
        optdec = new javax.swing.JRadioButton();
        optbin = new javax.swing.JRadioButton();
        optoct = new javax.swing.JRadioButton();
        opthex = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InSearch = new javax.swing.JTextField();
        sort = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sortlist = new javax.swing.JList<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Converter by Andy Huang");
        setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Converter");

        jLabel2.setText("Masukan Angka");

        InputAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAngkaActionPerformed(evt);
            }
        });

        button.setText("Convert");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        tableout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Decimal", "Binary", "Octal", "Hexadecimal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableout);

        optdec.setText("Decimal");
        optdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optdecActionPerformed(evt);
            }
        });

        optbin.setText("Binary");
        optbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optbinActionPerformed(evt);
            }
        });

        optoct.setText("Octal");
        optoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optoctActionPerformed(evt);
            }
        });

        opthex.setText("Hexadecimal");
        opthex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opthexActionPerformed(evt);
            }
        });

        jLabel3.setText("Pilih Basis Bilangan ( Number Base) :");

        jLabel4.setText("Masukan Angka yang Ingin di Cari Dalam Decimal :");

        sort.setText("SORTING (Hanya Decimal)");
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(sortlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(InSearch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAngka))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optdec)
                            .addComponent(optbin))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opthex)
                            .addComponent(optoct)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sort)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optdec)
                    .addComponent(optoct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optbin)
                    .addComponent(opthex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optdecActionPerformed
    optbin.setSelected(false);
    optoct.setSelected(false);
    opthex.setSelected(false);
    }//GEN-LAST:event_optdecActionPerformed

    private void optbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optbinActionPerformed
    optdec.setSelected(false);
    optoct.setSelected(false);
    opthex.setSelected(false);
    }//GEN-LAST:event_optbinActionPerformed

    private void optoctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optoctActionPerformed
    optdec.setSelected(false);
    optbin.setSelected(false);
    opthex.setSelected(false);
    }//GEN-LAST:event_optoctActionPerformed

    private void opthexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opthexActionPerformed
    optbin.setSelected(false);
    optoct.setSelected(false);
    optdec.setSelected(false);
    }//GEN-LAST:event_opthexActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

    System.out.println("Ini Hasil dari Konversi Anda : ");
        if(InputAngka.getText().isEmpty()){
        JOptionPane.showMessageDialog(this,
                            "Data Input Tidak Boleh Kosong !!! ",
                            "Warning",
                            JOptionPane.WARNING_MESSAGE);
        System.err.println("Data Input Tidak Boleh Kosong !!!");
         return;
    }
    if (!optdec.isSelected() && !optbin.isSelected() && !optoct.isSelected() && !opthex.isSelected()){
        JOptionPane.showMessageDialog(this,
                            "Pilih Jenis Basis Bilangan Data Tersebut !!! ",
                            "Warning",
                            JOptionPane.WARNING_MESSAGE);
        System.err.println("Pilih Jenis Basis Bilangan Data Tersebut !!!");
         return;    
        }
        try {
        TableManage tm = new TableManage(tableout);
        LinkedList <Object> list = new LinkedList<Object>();
        if (optdec.isSelected()){
            list.add(Integer.parseInt(InputAngka.getText()));
            list.add(Converter.DecToBin((int) list.get(0))); 
            list.add(Converter.DecToOct((int) list.get(0)));
            list.add(Converter.DecToHex((int) list.get(0)));
            tm.addRow(new Object[]{list.get(0),list.get(1),list.get(2),list.get(3)});
            System.out.println("Desimal : "+ list.get(0));
            System.out.print("Biner : ");
            Rekursif.DesimalToBiner((int) list.get(0));
            System.out.println("\nOctal : "+ list.get(2));
            System.out.println("Hexadesimal : "+ list.get(3));
            nlist.add (new Object []{list.get(0),list.get(1),list.get(2),list.get(3)});
        }
        if (optbin.isSelected()){
            list.add(Integer.parseInt(InputAngka.getText()));
            list.add(Converter.BinToDec((int) list.get(0))); 
            list.add(Converter.BinToOct((int) list.get(0)));
            list.add(Converter.BinToHex((int) list.get(0)));
            tm.addRow(new Object[]{list.get(1),list.get(0),list.get(2),list.get(3)});
            System.out.println("Desimal : "+ list.get(1));
            System.out.println("Biner : "+ list.get(0));
            System.out.println("Octal : "+ list.get(2));
            System.out.println("Hexadesimal : "+ list.get(3));
            nlist.add (new Object []{list.get(1),list.get(0),list.get(2),list.get(3)});
        }
        if (optoct.isSelected()){
            list.add(Integer.parseInt(InputAngka.getText()));
            list.add(Converter.OctToDec((int) list.get(0))); 
            list.add(Converter.OctToBin((int) list.get(0)));
            list.add(Converter.OctToHex((int) list.get(0)));
            tm.addRow(new Object[]{list.get(1),list.get(2),list.get(0),list.get(3)});
            System.out.println("Desimal : "+ list.get(1));
            System.out.println("Biner : "+ list.get(2));
            System.out.println("Octal : "+ list.get(0));
            System.out.println("Hexadesimal : "+ list.get(3));
            nlist.add (new Object []{list.get(1),list.get(2),list.get(0),list.get(3)});
        }
        if (opthex.isSelected()){
            list.add(InputAngka.getText());
            list.add(Converter.HexToDec((String) list.get(0))); 
            list.add(Converter.HexToBin((String) list.get(0)));
            list.add(Converter.HexToOct((String) list.get(0)));
            tm.addRow(new Object[]{list.get(1),list.get(2),list.get(3),list.get(0)});
            System.out.println("Desimal : "+ list.get(1));
            System.out.println("Biner : "+ list.get(2));
            System.out.println("Octal : "+ list.get(3));
            System.out.println("Hexadesimal : "+ list.get(0));
            nlist.add (new Object []{list.get(1),list.get(2),list.get(3),list.get(0)});
        }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,
                            "Data Tidak Sesuai Dengan Basis Bilangannya  !!! \nAtau Melebihi Limit Data",
                            "Warning",
                            JOptionPane.WARNING_MESSAGE);
                System.err.println("Data Tidak Sesuai Dengan Basis Bilangannya  !!! \nAtau Melebihi Limit Data");
            }
        
    }//GEN-LAST:event_buttonActionPerformed

    private void InputAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAngkaActionPerformed

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        String hasil = "";
        for(int i=0; i<nlist.size(); i++){
            if (hasil.equalsIgnoreCase("")){ 
                hasil=nlist.get(i)[0].toString();
            }
            else {
                hasil=hasil+","+nlist.get(i)[0].toString();
                    }
        }
        int [] data = Sorting.getas(hasil, nlist.size());
        ListManage lm = new ListManage(sortlist);
        System.out.println("Hasil Sort Desimal : ");
        for(int i=0; i<nlist.size(); i++){
            lm.addItem(data [i]);
            System.out.println(data [i]);
        }
        
    }//GEN-LAST:event_sortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InSearch;
    private javax.swing.JTextField InputAngka;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton optbin;
    private javax.swing.JRadioButton optdec;
    private javax.swing.JRadioButton opthex;
    private javax.swing.JRadioButton optoct;
    private javax.swing.JButton sort;
    private javax.swing.JList<String> sortlist;
    private javax.swing.JTable tableout;
    // End of variables declaration//GEN-END:variables
}

